repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff-check
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.63
    hooks:
      - id: ty
        pass_filenames: false
        always_run: true
